services:
  vulnerable-web:
    build:
      context: ./lab/target
    image: rowdyhacks/ctem-vulnerable-httpd:2.4.49
    ports:
      - "127.0.0.1:8080:80"
    networks:
      lab:
        aliases:
          - vulnerable-web.ctem.local

  httpd-250-internal:
    build:
      context: ./lab/target-250
    image: rowdyhacks/ctem-httpd-250:lab
    networks:
      - lab

  struts-internal:
    image: vulhub/struts2:2.3.30
    networks:
      - lab

networks:
  lab:
    driver: bridge
